services:
  # API en C# (.NET 10)
  api:
    build: .
    container_name: api_container
    ports:
      - "5217:8080" # Tu React busca el 5217 en tu PC
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      # Cambiamos el Host para que apunte a tu Windows Nativo:
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Port=5432;Database=users;Username=postgres;Password=PUTA0011